//! AI Context Generator — sanitized environment metadata for AI agents.
//!
//! Generates context maps in Markdown and JSON formats that include
//! variable names, types, descriptions, and examples — but **never**
//! actual sensitive values.

use crate::state::vault_state::VaultState;
use crate::vault::crypto::SecureKey;
use crate::vault::vault_db::{VaultDb, VaultDbError};
use serde::{Deserialize, Serialize};
use tauri::State;

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AiContextVariable {
    pub key: String,
    pub var_type: String,
    pub required: bool,
    pub sensitive: bool,
    pub description: String,
    /// Example value (redacted for sensitive vars)
    pub example: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AiContext {
    pub project_id: String,
    pub env: String,
    pub variables: Vec<AiContextVariable>,
    pub total_count: usize,
    pub sensitive_count: usize,
}

/// Generate an AI-safe context from vault variables.
pub fn generate_context(
    dek: &SecureKey,
    vault_db: &VaultDb,
    project_id: &str,
    env: &str,
) -> Result<AiContext, VaultDbError> {
    let variables = vault_db.get_variables(dek, project_id, env)?;
    let total_count = variables.len();
    let sensitive_count = variables.iter().filter(|v| v.sensitive).count();

    let context_vars: Vec<AiContextVariable> = variables
        .into_iter()
        .map(|v| {
            let example = if v.sensitive {
                generate_mock_example(&v.var_type, &v.key)
            } else {
                v.value.clone()
            };

            AiContextVariable {
                key: v.key,
                var_type: v.var_type,
                required: v.required,
                sensitive: v.sensitive,
                description: v.description,
                example,
            }
        })
        .collect();

    Ok(AiContext {
        project_id: project_id.to_string(),
        env: env.to_string(),
        variables: context_vars,
        total_count,
        sensitive_count,
    })
}

/// Generate context as Markdown (.env.md format).
pub fn context_to_markdown(ctx: &AiContext) -> String {
    let mut lines = Vec::new();
    lines.push(format!("# Environment: {}", ctx.env));
    lines.push(String::new());
    lines.push(format!(
        "> {} variables ({} sensitive — values redacted)",
        ctx.total_count, ctx.sensitive_count
    ));
    lines.push(String::new());
    lines.push("| Variable | Type | Required | Sensitive | Description | Example |".to_string());
    lines.push("|---|---|---|---|---|---|".to_string());

    for v in &ctx.variables {
        lines.push(format!(
            "| `{}` | {} | {} | {} | {} | `{}` |",
            v.key,
            v.var_type,
            if v.required { "✅" } else { "❌" },
            if v.sensitive { "🔒" } else { "—" },
            if v.description.is_empty() {
                "—"
            } else {
                &v.description
            },
            v.example,
        ));
    }

    lines.push(String::new());
    lines.push("*Generated by Varlock — sensitive values are redacted.*".to_string());
    lines.join("\n")
}

/// Generate context as JSON (.env.context.json format).
pub fn context_to_json(ctx: &AiContext) -> Result<String, VaultDbError> {
    serde_json::to_string_pretty(ctx).map_err(|e| {
        VaultDbError::Crypto(crate::vault::crypto::CryptoError::InvalidData(format!(
            "JSON serialization failed: {}",
            e
        )))
    })
}

/// Generate a safe mock/example value based on type and key name.
fn generate_mock_example(var_type: &str, key: &str) -> String {
    let lower = key.to_lowercase();

    // Try to infer from key name first
    if lower.contains("stripe") {
        return "sk_test_xxxxxxxxxxxx".to_string();
    }
    if lower.contains("jwt") || lower.contains("token") {
        return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.xxxxx".to_string();
    }
    if lower.contains("database") || lower.contains("db_url") || lower.contains("database_url") {
        return "postgres://user:****@localhost:5432/dbname".to_string();
    }
    if lower.contains("api_key") || lower.contains("apikey") {
        return "sk-xxxxxxxxxxxxxxxxxxxx".to_string();
    }
    if lower.contains("password") || lower.contains("passwd") {
        return "********".to_string();
    }
    if lower.contains("email") {
        return "user@example.com".to_string();
    }

    // Fall back to type
    match var_type {
        "url" => "https://example.com/api".to_string(),
        "port" => "3000".to_string(),
        "boolean" => "true".to_string(),
        "number" => "42".to_string(),
        _ => "[REDACTED]".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::vault::vault_db::VaultDb;

    #[test]
    fn test_ai_context_redacts_sensitive() {
        let db = VaultDb::open_in_memory().unwrap();
        let dek = db.setup("test").unwrap();

        db.set_variable(
            &dek, "p1", "dev", "PORT", "3000", "port", false, true, "App port",
        )
        .unwrap();
        db.set_variable(
            &dek,
            "p1",
            "dev",
            "STRIPE_KEY",
            "sk_live_REAL_SECRET",
            "string",
            true,
            true,
            "Stripe API key",
        )
        .unwrap();

        let ctx = generate_context(&dek, &db, "p1", "dev").unwrap();
        assert_eq!(ctx.total_count, 2);
        assert_eq!(ctx.sensitive_count, 1);

        let port_var = ctx.variables.iter().find(|v| v.key == "PORT").unwrap();
        assert_eq!(port_var.example, "3000"); // non-sensitive: real value

        let stripe_var = ctx
            .variables
            .iter()
            .find(|v| v.key == "STRIPE_KEY")
            .unwrap();
        assert!(!stripe_var.example.contains("REAL_SECRET")); // sensitive: redacted
        assert!(stripe_var.example.contains("sk_test")); // mock value
    }

    #[test]
    fn test_markdown_format() {
        let db = VaultDb::open_in_memory().unwrap();
        let dek = db.setup("test").unwrap();
        db.set_variable(&dek, "p1", "dev", "PORT", "3000", "port", false, true, "")
            .unwrap();

        let ctx = generate_context(&dek, &db, "p1", "dev").unwrap();
        let md = context_to_markdown(&ctx);

        assert!(md.contains("# Environment: dev"));
        assert!(md.contains("PORT"));
        assert!(md.contains("port"));
    }
}

// ── Tauri Commands ──

/// Generate AI context as JSON.
#[tauri::command]
pub fn ai_context_json(
    vault: State<'_, VaultState>,
    project_id: String,
    env_name: String,
) -> Result<String, String> {
    let dek = vault.require_dek()?;
    let ctx =
        generate_context(&dek, &vault.db, &project_id, &env_name).map_err(|e| e.to_string())?;
    context_to_json(&ctx).map_err(|e| e.to_string())
}

/// Generate AI context as Markdown.
#[tauri::command]
pub fn ai_context_markdown(
    vault: State<'_, VaultState>,
    project_id: String,
    env_name: String,
) -> Result<String, String> {
    let dek = vault.require_dek()?;
    let ctx =
        generate_context(&dek, &vault.db, &project_id, &env_name).map_err(|e| e.to_string())?;
    Ok(context_to_markdown(&ctx))
}

/// Get AI context as structured data.
#[tauri::command]
pub fn ai_context_data(
    vault: State<'_, VaultState>,
    project_id: String,
    env_name: String,
) -> Result<AiContext, String> {
    let dek = vault.require_dek()?;
    generate_context(&dek, &vault.db, &project_id, &env_name).map_err(|e| e.to_string())
}
